# Generated by Django 5.2.6 on 2025-10-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(choices=[('basico', 'BASICO'), ('avandazo', 'Avanzado'), ('premium', 'PREMIUM')], max_length=20)),
                ('clases_Mensuales', models.PositiveIntegerField(blank=True, null=True)),
                ('ilimitado', models.BooleanField(default=False)),
            ],
        ),
    ]
