# Generated by Django 5.2.6 on 2025-10-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='nombre_plan',
            field=models.CharField(choices=[('basico', 'BASICO'), ('avanzado', 'Avanzado'), ('premium', 'PREMIUM')], max_length=20),
        ),
    ]
