# Generated by Django 5.2.6 on 2025-10-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0002_alter_plan_nombre_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='nombre_plan',
            field=models.CharField(max_length=50),
        ),
    ]
