# Generated by Django 5.2.6 on 2025-10-20 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0003_alter_plan_nombre_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[\\wÁÉÍÓÚáéíóúÑñ\\s\\-]+$', 'Solo letras/números/espacios/guiones.')])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
