# Generated by Django 5.2.6 on 2025-10-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0004_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='profesor',
            field=models.CharField(blank=True, help_text='Nombre del profesor responsable de la actividad.', max_length=60, null=True),
        ),
    ]
