# Generated by Django 5.2.6 on 2025-10-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0005_actividad_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=60)),
                ('inicio', models.DateTimeField()),
                ('termino', models.DateTimeField()),
                ('estado', models.CharField(choices=[('terminada', 'terminada'), ('cancelada', 'cancelada'), ('programada', 'programada')], default='programada', max_length=20)),
            ],
        ),
    ]
