# Generated by Django 5.2.6 on 2025-11-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0006_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='profesor',
            field=models.CharField(blank=True, help_text='Nombre del profesor a cargo de la actividad.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='STKAA.actividad'),
        ),
    ]
