# Generated by Django 5.2.6 on 2025-11-09 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0007_alter_actividad_profesor_alter_clase_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='clase',
            name='actividad',
            field=models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='STKAA.actividad'),
        ),
    ]
