# Generated by Django 5.2.6 on 2025-11-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0008_clase_profesor_alter_clase_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='profesor',
        ),
    ]
