# Generated by Django 5.2.6 on 2025-11-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0010_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
