# Generated by Django 5.2.6 on 2025-11-15 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0011_usuario_email_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asistire', 'Asistiré'), ('cancelada', 'Cancelada')], default='asistire', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bokings', to='STKAA.clase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='STKAA.usuario')),
            ],
        ),
    ]
