# Generated by Django 5.2.6 on 2025-11-15 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0012_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='STKAA.clase'),
        ),
    ]
