# Generated by Django 5.2.6 on 2025-11-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STKAA', '0014_alter_actividad_nombre_alter_booking_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='profesor',
            field=models.CharField(blank=True, help_text='Nombre del profesor a cargo de la actividad.', max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='STKAA.clase'),
        ),
    ]
